### ISSUE TITLE
Crash on registration/log-in

### ISSUE THREAD

**Issue by nofoto** [Musicoll/Kiwi#158]
Kiwi crashes when I click Register having tried to create a username.

Mac Book Pro High Sierra OSX 10.13.6 (same also happens on my MacMini)

**Comment by jean-millot** [comment]
Hello,

Thank you for your feedback. Our server is currently faulty and due to lockdown restrictions we can’t access it properly. We will try to solve the issue as soon as we can have proper access to our server and will keep you posted.

In the meantime, you can still work with Kiwi offline.

Best regards,
Jean

**Comment by jean-millot** [comment]
Hello notofo,

Our server is back up. You should now be able to login the application.

Best regards,
Jean

**Comment by nofoto** [comment]
hi, thanks! - now Kiwi no longer crashes when I try to register but I get an error message saying 'Sending confirmation mail failed'

**Comment by jean-millot** [comment]
Hi, i just fixed this problem as well. I think you may be able to register now. Please tell me if the problem is solved so I can close this issue once done.

**Comment by nofoto** [comment]
Fixed! Thanks!
